version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - APP_KEY=your-app-key
      - DB_HOST=db
      - DB_DATABASE=your-db-name
      - DB_USERNAME=your-db-username
      - DB_PASSWORD=your-db-password
    restart: always

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=your-db-name
      - MYSQL_USER=your-db-username
      - MYSQL_PASSWORD=your-db-password
      - MYSQL_ROOT_PASSWORD=your-root-password
    restart: always
