name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: your-ec2-instance-ip
          username: ec2-user
          key: ${{ secrets.YOUR_SSH_PRIVATE_KEY }}

      - name: Update Docker Compose and restart containers
        run: |
          scp docker-compose.yml ec2-user@your-ec2-instance-ip:/home/ec2-user/docker-compose.yml
          ssh ec2-user@your-ec2-instance-ip "docker-compose -f /home/ec2-user/docker-compose.yml down"
          ssh ec2-user@your-ec2-instance-ip "docker-compose -f /home/ec2-user/docker-compose.yml up -d"
