name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: your-docker-repository/image-name:latest

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.3.0
        with:
          host: your-ec2-instance-ip
          username: your-ec2-username
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: .
          target: /home/ubuntu/your-app-folder
